name: Refresh Snapshots

on:
  schedule:
    - cron: "0 6 * * *"      # every day at 06:00 UTC
  workflow_dispatch: {}      # allow manual runs from the Actions tab

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Stage 1: scrape free and paid charts
      - name: Scrape top free
        run: |
          python app_store_scraper_v2.py \
            --collection top-free \
            --all-categories \
            --limit 100 \
            --note "GitHub Action top-free"

      - name: Scrape top paid
        run: |
          python app_store_scraper_v2.py \
            --collection top-paid \
            --all-categories \
            --limit 100 \
            --note "GitHub Action top-paid"

      # Stage 1.5: reuse previous scores
      - name: Reuse existing Stage 2 scores
        run: python scripts/reuse_stage2_scores.py --log-level INFO

      # Stage 2: score remaining apps
      - name: Stage 2 scoring
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python app_stage2_analysis.py

      # Materialize deltas into DB
      - name: Build snapshot deltas
        run: python analysis/build_deltas.py

      # Option 1: Commit the updated DB back to the repo
      - name: Commit database
        env:
          GIT_COMMIT_USER: ${{ secrets.GIT_COMMIT_USER || 'github-actions[bot]' }}
          GIT_COMMIT_EMAIL: ${{ secrets.GIT_COMMIT_EMAIL || 'github-actions[bot]@users.noreply.github.com' }}
        run: |
          git config user.name "$GIT_COMMIT_USER"
          git config user.email "$GIT_COMMIT_EMAIL"
          git add exports/app_store_apps_v2.db
          git commit -m "Automated snapshot refresh" || echo "Nothing to commit"

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Option 2 (instead of committing): Upload DB as an artifact
      # - name: Upload updated DB
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app_store_apps_v2.db
      #     path: exports/app_store_apps_v2.db
